# =============================================================================
# zzta-config.cmake — CMake Package Configuration for zonal-zero-trust-authenticator
#
# Allows integrating projects to use:
#   find_package(zzta 1.0.0 REQUIRED)
#   target_link_libraries(my_target PRIVATE zzta::zzta_core)
#
# This file is installed to:
#   <prefix>/lib/cmake/zzta/zzta-config.cmake
#
# (c) 2026 norxs Technology LLC. All rights reserved.
# =============================================================================

cmake_minimum_required(VERSION 3.20)

# Guard against multiple inclusion
if(TARGET zzta::zzta_core)
    return()
endif()

# ── Version compatibility check ───────────────────────────────────────────────
# PACKAGE_VERSION set by zzta-config-version.cmake (generated by CMakePackageConfigHelpers)
# Compatible if major version matches and minor >= requested minor.
include("${CMAKE_CURRENT_LIST_DIR}/zzta-config-version.cmake" OPTIONAL)

# ── Locate the installed static library ───────────────────────────────────────
get_filename_component(_ZZTA_INSTALL_PREFIX
    "${CMAKE_CURRENT_LIST_DIR}/../../../"
    ABSOLUTE)

find_library(_ZZTA_CORE_LIB
    NAMES zzta_core libzzta_core
    PATHS "${_ZZTA_INSTALL_PREFIX}/lib"
    NO_DEFAULT_PATH
)

if(NOT _ZZTA_CORE_LIB)
    set(zzta_FOUND FALSE)
    if(zzta_FIND_REQUIRED)
        message(FATAL_ERROR
            "zzta: Could not find libzzta_core in ${_ZZTA_INSTALL_PREFIX}/lib.\n"
            "Ensure the library was built and installed with:\n"
            "  cmake --install <build-dir>")
    endif()
    return()
endif()

# ── Create imported target ─────────────────────────────────────────────────────
add_library(zzta::zzta_core STATIC IMPORTED GLOBAL)

set_target_properties(zzta::zzta_core PROPERTIES
    IMPORTED_LOCATION                "${_ZZTA_CORE_LIB}"
    INTERFACE_INCLUDE_DIRECTORIES    "${_ZZTA_INSTALL_PREFIX}/include"
    INTERFACE_COMPILE_FEATURES       "cxx_std_14"
)

# ── Propagate AUTOSAR compile requirements ─────────────────────────────────────
# Integrating targets that link zzta::zzta_core will automatically inherit
# the CXX standard requirement (C++14) and must not enable exceptions or RTTI.
target_compile_features(zzta::zzta_core INTERFACE cxx_std_14)

# ── Report success ─────────────────────────────────────────────────────────────
set(zzta_FOUND TRUE)
set(zzta_VERSION "1.0.0")
set(zzta_INCLUDE_DIRS "${_ZZTA_INSTALL_PREFIX}/include")
set(zzta_LIBRARIES zzta::zzta_core)

if(NOT zzta_FIND_QUIETLY)
    message(STATUS "Found zzta v${zzta_VERSION}: ${_ZZTA_CORE_LIB}")
endif()
